### ISSUE TITLE
Unexpected identifier SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by dolphinfine** [cheneyweb/parcel-vue#1]
兄弟为什么我这里报这个错误
![image](https://user-images.githubusercontent.com/27426130/35032064-7b24b8a4-fba0-11e7-87c2-510bcf69c06d.png)

**Comment by EvenRsh** [comment]
同样的错误,无从处理

**Comment by cheneyweb** [comment]
最新的CLI工具，已经更新至Parcel 1.7.0 版本以上，支持原生VUE构建，不再需要parcel-vue-plugin就可以构建VUE项目，真正零配置
