### ISSUE TITLE
/mypro/src/main.js: Cannot read property 'targets' of undefined

### ISSUE THREAD

**Issue by lusess123** [cheneyweb/parcel-vue#3]
/Documents/demo/mypro/mypro/src/main.js: Cannot read property 'targets' of undefined
    at loadBabelrc (/Documents/demo/mypro/mypro/node_modules/parcel-bundler/src/utils/getTargetEngines.js:113:23)
    at <anonymous>

这个怎么解决

**Comment by cheneyweb** [comment]
最新的CLI工具，已经更新至Parcel 1.7.0 版本以上，支持原生VUE构建，不再需要parcel-vue-plugin就可以构建VUE项目，真正零配置
